class UpdateGamesTable < ActiveRecord::Migration
  def self.up
    change_table :games do |t|
      t.string :name
      t.remove :tom_x
      t.remove :felix_x
      t.remove :tom_y
      t.remove :felix_y
      t.remove :fexlix_score
      t.remove :tom_lives
      t.remove :felix_lives
      t.remove :tom_bombs
      t.remove :felix_bombs
      t.integer :lifeTom
      t.integer :lifeFelix
      t.integer :scoreTom
      t.integer :scoreFelix
      t.text    :board
      t.integer :FelixX
      t.integer :FelixY
      t.integer :TomX
      t.integer :TomY
      t.integer :MouseX
      t.integer :MouseY
      t.integer :TomBombX
      t.integer :TomBombY
      t.integer :TomArrowX
      t.integer :TomArrowY
      t.integer :FelixBombX
      t.integer :FelixBombY
      t.integer :FelixArrowX
      t.integer :FelixArrowY
      t.integer :TomAddon
      t.integer :FelixAddon
      t.integer :Tom_bomb_activate
      t.integer :Felix_bomb_activate
      t.integer :Tom_bomb_explode
      t.integer :Felix_bomb_explode
      t.integer :Tom_arrow_activate
      t.integer :Felix_arrow_activate
      t.integer :TomBdir
      t.integer :FelixBdir
      t.integer :TbombMove
      t.integer :TarrowMove
      t.integer :FbombMove
      t.integer :FarrowMove
      t.integer :TmoveCount
      t.integer :TAMCount
      t.integer :FmoveCount
      t.integer :FAMCount
      t.integer :TomBcount
      t.integer :TomAcount
      t.integer :FelixBcount
      t.integer :FelixAcount
      t.integer :TomBcheck
      t.integer :TomAcheck
      t.integer :FelixBcheck
      t.integer :FelixAcheck
      t.integer :checklife
      t.integer :tossWinner
    end
  end

  def self.down
    change_table :games do |t|
      #t.remove :name
      t.integer :tom_x
      t.integer :felix_x
      t.integer :tom_y
      t.integer :felix_y
      t.integer :fexlix_score
      t.integer :tom_lives
      t.integer :felix_lives
      t.integer :tom_bombs
      t.integer :felix_bombs
      t.remove :lifeTom
      t.remove :lifeFelix
      t.remove :scoreTom
      t.remove :scoreFelix
      t.remove    :board
      t.remove :FelixX
      t.remove :FelixY
      t.remove :TomX
      t.remove :TomY
      t.remove :MouseX
      t.remove :MouseY
      t.remove :TomBombX
      t.remove :TomBombY
      t.remove :TomArrowX
      t.remove :TomArrowY
      t.remove :FelixBombX
      t.remove :FelixBombY
      t.remove :FelixArrowX
      t.remove :FelixArrowY
      t.remove :TomAddon
      t.remove :FelixAddon
      t.remove :Tom_bomb_activate
      t.remove :Felix_bomb_activate
      t.remove :Tom_bomb_explode
      t.remove :Felix_bomb_explode
      t.remove :Tom_arrow_activate
      t.remove :Felix_arrow_activate
      t.remove :TomBdir
      t.remove :FelixBdir
      t.remove :TbombMove
      t.remove :TarrowMove
      t.remove :FbombMove
      t.remove :FarrowMove
      t.remove :TmoveCount
      t.remove :TAMCount
      t.remove :FmoveCount
      t.remove :FAMCount
      t.remove :TomBcount
      t.remove :TomAcount
      t.remove :FelixBcount
      t.remove :FelixAcount
      t.remove :TomBcheck
      t.remove :TomAcheck
      t.remove :FelixBcheck
      t.remove :FelixAcheck
      t.remove :checklife
      t.remove :tossWinner
    end
  end
end
